spring.application.name=notification-app

affordmed.token=Replace_with_mytoken 
#replace the token with the given token as i am not pushing into github it can down the token access that why please see to it evaluator 